Calculate Remaining Seconds from Interval value
Daegalus/dart-otp pull request #35
Opened 2022-01-02 20:48 UTC by AkbarAsghari

Remaining Time
There is a property that will tell you how much time remains in the current time step window in seconds

2022-01-02 21:42 UTC, Daegalus requested changes
This is a great idea but I think we can adjust how this is implemented to make it more consistent.

What are your thoughts on the following:

Make a new function called `remainingSeconds()` that takes an optional time and interval. That uses current time to figure out remaining seconds using a default 30 second interval.

This way you can always get the exact remaining window, regardless of the code generated or when the last code was generated.

Let me know what you think.

2022-01-02 21:42 UTC, Daegalus commented on lib/otp.dart
> +    remainingSeconds = interval - (((time ~/ 1000).round()) % interval).floor();
My only concern here is this will only update the remaining seconds if you generate a new code.

Maybe we should make a new function?

2022-01-02 21:50 UTC, AkbarAsghari commented on lib/otp.dart
> +    remainingSeconds = interval - (((time ~/ 1000).round()) % interval).floor();
yes problem is **Statics**
but don't worry no one generate two type of TOTP in one method

2022-01-02 22:00 UTC, AkbarAsghari commented on lib/otp.dart
> +    remainingSeconds = interval - (((time ~/ 1000).round()) % interval).floor();
property is clean but I'll write function now

2022-01-02 22:13 UTC, AkbarAsghari commented
replace remainSecounds property with remainSecounds() function with default value of interval (30)

2022-01-02 22:26 UTC, Daegalus approved these changes

2022-01-02 22:26 UTC, Daegalus commented
Awesome, thanks, I'll get a new release out tonight when I get home from errands.

2022-01-03 00:09 UTC, merged

2022-01-03 00:24 UTC, Daegalus commented
All set, 3.0.2 should have your contribution, thank you